### ISSUE TITLE
The header of the copywrith is wrong.

### ISSUE THREAD

**Issue by jzeferino** [massivedisaster/DiagonalDrawable#2]
Should update the copy header copyright:

>  * DiagonalDrawable - A set of Android libraries to help speed up Android development.

**Comment by extmkv** [comment]
I know, we have the same problem in `ArcToolbarView`

**Comment by jzeferino** [comment]
Yes, I've already created https://github.com/massivedisaster/ArcToolbarView/issues/14 there.
